version: '3'

services:
  
  memcached:
    image: memcached:1.4-alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure  
    networks:
      - shopnc-test

  redis:
    image: redis:3.2-alpine
    volumes:
      - /mydata/jenkinsci/swarm/shopnc-test/shopnc-swarm/conf/redis/redis.conf:/etc/redis.conf
      - redis:/data
    command: redis-server /etc/redis.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
      - shopnc-test

  shopnc:
    image: magichuihui/shopnc:v1.0
    working_dir: /projects
    volumes:
      - /mydata/jenkinsci/swarm/shopnc-test/shopnc-swarm/conf/php56/php.ini:/usr/local/etc/php/php.ini
      - /mydata/jenkinsci/swarm/shopnc-test/shopnc-swarm/conf/php56/php-fpm.conf:/usr/local/etc/php-fpm.conf
      - /mydata/jenkinsci/swarm/shopnc-test/app:/projects
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
    depends_on:
      - redis
    env_file:
      - variables.env
    networks:
      - shopnc-test

  nginx-server:
    image: openresty/openresty:1.13.6.1-centos
    volumes:
      - /mydata/jenkinsci/swarm/shopnc-test/app:/projects
      - /mydata/jenkinsci/swarm/shopnc-test/shopnc-swarm/conf/nginx:/usr/local/openresty/nginx/conf
    deploy:
      replicas: 3
      restart_policy: 
        condition: on-failure
    depends_on:
      - shopnc
    ports:
      - 50080:80
    networks:
      - shopnc-test

volumes:
  redis:
    driver: local

networks:
  shopnc-test:
    driver: overlay
